<?php

namespace Omnipay\PayNKolay\Helpers;

class PayNKolayHelper
{
    /**
     * SHA-512 over the input, base64-encoded. Used by every outgoing
     * `hashDatav2` field.
     */
    public static function hash(string $data): string
    {
        return base64_encode(hash('sha512', $data, true));
    }

    /**
     * Hash for /Vpos/v1/Payment (Purchase v1) and /Vpos/by-link-create
     * (Pay By Link).
     *
     * Format: sx|clientRefCode|amount|successUrl|failUrl|rnd|customerKey|merchantSecretKey
     */
    public static function generateSaleHash(
        string $sx,
        string $clientRefCode,
        string $amount,
        string $successUrl,
        string $failUrl,
        string $rnd,
        string $customerKey,
        string $merchantSecretKey
    ): string {
        return self::hash(implode('|', [
            $sx,
            $clientRefCode,
            $amount,
            $successUrl,
            $failUrl,
            $rnd,
            $customerKey,
            $merchantSecretKey,
        ]));
    }

    /**
     * Hash for /Vpos/v1/CancelRefundPayment.
     *
     * Format: sx|referenceCode|type|amount|trxDate|merchantSecretKey
     * trxDate format: YYYY.MM.DD
     */
    public static function generateCancelRefundHash(
        string $sx,
        string $referenceCode,
        string $type,
        string $amount,
        string $trxDate,
        string $merchantSecretKey
    ): string {
        return self::hash(implode('|', [
            $sx,
            $referenceCode,
            $type,
            $amount,
            $trxDate,
            $merchantSecretKey,
        ]));
    }

    /**
     * Hash for /Vpos/Payment/GetMerchandInformation.
     *
     * Format: sx|date|merchantSecretKey
     * date format: DD.MM.YYYY
     */
    public static function generateMerchantInfoHash(
        string $sx,
        string $date,
        string $merchantSecretKey
    ): string {
        return self::hash(implode('|', [
            $sx,
            $date,
            $merchantSecretKey,
        ]));
    }

    /**
     * Hash for the inbound 3DS/non-3DS result postback — the `hashDataV2`
     * field. This is the scheme Paynkolay documents on
     * https://paynkolay.com.tr/entegrasyon/05-hash-response.php and the one
     * merchants are told to verify:
     *
     *   MERCHANT_NO|REFERENCE_CODE|AUTH_CODE|RESPONSE_CODE|USE_3D|RND
     *     |INSTALLMENT|AUTHORIZATION_AMOUNT|CURRENCY_CODE|MERCHANT_SECRET_KEY
     *
     * SHA-512 over the UTF-8 string, base64-encoded — same as every outgoing
     * `hashDatav2`. Note the `RND` echoed back is generated by Paynkolay and
     * differs from the one sent in the request.
     */
    public static function generateResponseHashV2(
        string $merchantNo,
        string $referenceCode,
        string $authCode,
        string $responseCode,
        string $use3D,
        string $rnd,
        string $installment,
        string $authorizationAmount,
        string $currencyCode,
        string $merchantSecretKey
    ): string {
        return self::hash(implode('|', [
            $merchantNo,
            $referenceCode,
            $authCode,
            $responseCode,
            $use3D,
            $rnd,
            $installment,
            $authorizationAmount,
            $currencyCode,
            $merchantSecretKey,
        ]));
    }

    /**
     * Legacy `hashData` postback hash (SHA-1, hex-decode, base64, raw
     * concatenation with no separator). Paynkolay still emits this field
     * alongside `hashDataV2` but does not document how it is built; the field
     * order below was reverse-engineered from a WooCommerce plugin and is NOT
     * reliable — real postbacks fail to match it.
     *
     * @deprecated Verify `hashDataV2` via {@see generateResponseHashV2()}.
     */
    public static function generatePostbackHash(
        string $merchantNo,
        string $referenceCode,
        string $authCode,
        string $responseCode,
        string $use3D,
        string $rnd,
        string $installment,
        string $authorizationAmount,
        string $merchantSecretKey
    ): string {
        $hashString = $merchantNo
            . $referenceCode
            . $authCode
            . $responseCode
            . $use3D
            . $rnd
            . $installment
            . $authorizationAmount
            . $merchantSecretKey;

        return base64_encode(pack('H*', sha1($hashString)));
    }

    /**
     * Verify an inbound result postback against the merchant secret key.
     *
     * Only `hashDataV2` is authoritative. `CURRENCY_CODE` is part of the
     * hashed string but is absent from some postbacks (notably the 3D
     * AutoComplete return); when it is missing we accept either the empty
     * segment or the segment being dropped altogether, since both candidates
     * still require knowledge of the secret key.
     *
     * Returns false when `hashDataV2` is missing, the secret is empty, or no
     * candidate matches.
     *
     * @param array<string, mixed> $postback
     */
    public static function verifyPostbackHash(array $postback, string $merchantSecretKey): bool
    {
        if ($merchantSecretKey === '') {
            return false;
        }

        $supplied = (string) ($postback['hashDataV2'] ?? '');

        if ($supplied === '') {
            return false;
        }

        $fields = [
            (string) ($postback['MERCHANT_NO'] ?? ''),
            (string) ($postback['REFERENCE_CODE'] ?? ''),
            (string) ($postback['AUTH_CODE'] ?? ''),
            (string) ($postback['RESPONSE_CODE'] ?? ''),
            (string) ($postback['USE_3D'] ?? ''),
            (string) ($postback['RND'] ?? ''),
            (string) ($postback['INSTALLMENT'] ?? ''),
            (string) ($postback['AUTHORIZATION_AMOUNT'] ?? ''),
        ];

        $candidates = [];

        $currencyCode = (string) ($postback['CURRENCY_CODE'] ?? '');

        $candidates[] = self::hash(implode('|', [...$fields, $currencyCode, $merchantSecretKey]));

        if (! isset($postback['CURRENCY_CODE'])) {
            $candidates[] = self::hash(implode('|', [...$fields, $merchantSecretKey]));
        }

        foreach ($candidates as $candidate) {
            if (hash_equals($candidate, $supplied)) {
                return true;
            }
        }

        return false;
    }

    /**
     * Format amount with two decimals and dot separator (e.g. 100.5 -> "100.50").
     */
    public static function formatAmount(float $amount): string
    {
        return number_format($amount, 2, '.', '');
    }

    /**
     * Strip escaped newlines/quotes the gateway emits inside HTML payloads.
     */
    public static function cleanHtml(?string $input): ?string
    {
        if (empty($input)) {
            return $input;
        }

        return trim(str_replace(
            ['\\r', '\\n', "\r", "\n", '\\"'],
            ['', '', '', '', '"'],
            $input
        ));
    }
}
